algorithm:
  noise_model_config: {}
  noise_model:
  constraints_model_config: {}
  constraints_model: febo.models.gp.GP
  model_config: {}
  model: febo.models.gp.GP

model:
  beta: 2
models.gp:
  noise_var: 0.01
  kernels:
    - - GPy.kern.RBF
      - variance: 1.0
        lengthscale: 0.2
        ARD: false
  calculate_gradients: true  # Enable/Disable computation of gradient on each update.


algorithm.subdomainbo:
  min_queries_line: 10
  max_queries_line: 40
  min_queries_tr: 2*d
  max_queries_tr: 2*d
  acquisition: febo.algorithms.subdomainbo.acquisition.ucb
  plot_every_step: false
  plot: true

algorithm.rembo:
  emb_d: 0
  interleaved_runs: 4

algorithm.nelder_mead:
  contraction_factor: 0.1

algorithm.safeopt:
  points_per_dimension: 100
  ucb: false

controller:
  best_predicted_every: 1
  T: 100 # Horizon
  repetitions: 1


environment.benchmark:
  noise_obs_mode: none  # Can be set to "full", "evaluation" or "hidden".
  noise_function: 0.01
  aug_d: 0
  lower_bound_objective: 0.4
  random_x0: false
  random_x0_min_value: 0.5
  dimension: 17
  constraints: 
  - gicosy.simulation_wrapper.MocadiConstraint1
  - gicosy.simulation_wrapper.MocadiConstraint2
  - gicosy.simulation_wrapper.MocadiConstraint3
  - gicosy.simulation_wrapper.MocadiConstraint4
  - gicosy.simulation_wrapper.MocadiConstraint5
  - gicosy.simulation_wrapper.MocadiConstraint6
  - gicosy.simulation_wrapper.MocadiConstraint7
  - gicosy.simulation_wrapper.MocadiConstraint8
  - gicosy.simulation_wrapper.MocadiConstraint9
  - gicosy.simulation_wrapper.MocadiConstraint10
  - gicosy.simulation_wrapper.MocadiConstraint11
  - gicosy.simulation_wrapper.MocadiConstraint12
  - gicosy.simulation_wrapper.MocadiConstraint13
  - gicosy.simulation_wrapper.MocadiConstraint14
  - gicosy.simulation_wrapper.MocadiConstraint15
  - gicosy.simulation_wrapper.MocadiConstraint16
  - gicosy.simulation_wrapper.MocadiConstraint17
  - gicosy.simulation_wrapper.MocadiConstraint18
  - gicosy.simulation_wrapper.MocadiConstraint19
  - gicosy.simulation_wrapper.MocadiConstraint20
  - gicosy.simulation_wrapper.MocadiConstraint21
  - gicosy.simulation_wrapper.MocadiConstraint22
  - gicosy.simulation_wrapper.MocadiConstraint23
  - gicosy.simulation_wrapper.MocadiConstraint24
  - gicosy.simulation_wrapper.MocadiConstraint25
  - gicosy.simulation_wrapper.MocadiConstraint26
  - gicosy.simulation_wrapper.MocadiConstraint27
  - gicosy.simulation_wrapper.MocadiConstraint28
  - gicosy.simulation_wrapper.MocadiConstraint29
  - gicosy.simulation_wrapper.MocadiConstraint30


experiment.multi:
  label: febo.labels.algorithm_name
  multi_controller: febo.controller.multi.RepetitionController
  iterator:
#  - experiment.simple:algorithm: febo.algorithms.NelderMead
#  - experiment.simple:algorithm: febo.algorithms.SafeRandomLineBO
  - experiment.simple:algorithm: febo.algorithms.SafeAscentLineBO
#  - experiment.simple:algorithm: febo.algorithms.SafeCoordinateLineBO
#  - experiment.simple:algorithm: febo.algorithms.UCB # just for reference
#  - experiment.simple:algorithm: febo.algorithms.safeopt.SwarmSafeOpt
  fixed_environment: false

experiment.simple:
  algorithm: febo.algorithms.Random
#  algorithm: febo.algorithms.UCB
  environment: febo.environment.benchmarks.functions.MocadiSimulation
  controller: febo.controller.simple.SimpleController


solver.grid:
  points_per_dimension: 300
solver.scipy:
  convergence_warnings: true
  sync_restarts: true
  num_processes: 1
  num_restart: 50
  lbfgs_maxfun: 1000
  lbfgs_use_gradients: false


main:
  log_level_file: INFO
  log_level_console: INFO
  experiment: febo.experiment.MultiExperiment  # Experiment
